# Generated by Django 4.1 on 2022-08-20 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_rename_evaluaiton_evaluation_evaluation_quiz_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum',
            old_name='name',
            new_name='course',
        ),
        migrations.CreateModel(
            name='Course_quiz_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('question', models.IntegerField()),
                ('answer', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
